Repository layerai/sdk, pull requests merged in 2022-08, with the labels that each got.

#285 Send audience from the SDK during login
  layer/auth.py
  layer/config/config_manager.py
  poetry.lock
  test/unit/test_auth.py
Labels: bug

#291 Adjust dependencies so Colab does not prompt to restart the runtime
  poetry.lock
  pyproject.toml
Labels: dependencies

#301 Do not redirect stdout to rich Console
  layer/tracker/output.py
Labels: bug

#320 Update dependency layer-api to 0.9.378152
  poetry.lock
  pyproject.toml
Labels: dependencies

#326 Add category parameter when logging data
  layer/clients/logged_data_service.py
  layer/logged_data/log_data_runner.py
  layer/main/log.py
  test/unit/logged_data/test_log_data_runner.py
Labels: enhancement

#345 Add API for getting logged data associated to a Model
  layer/clients/__init__.py
  layer/clients/data_catalog.py
  layer/clients/model_catalog.py
  layer/contracts/datasets.py
  layer/contracts/logged_data.py
  layer/contracts/models.py
  layer/logged_data/log_data_runner.py
  layer/main/asset.py
  layer/main/log.py
  layer/training/runtime/system_metrics.py
  test/unit/contracts/test_logged_data.py
  test/unit/decorators/util.py
  test/unit/logged_data/test_log_data_runner.py
  test/unit/test_dataset.py
Labels: enhancement

#362 Fail fast when running on Windows without WSL
  layer/main/utils.py
Labels: enhancement

#373 Allow empty return for datasets
  layer/clients/model_catalog.py
  layer/context.py
  layer/executables/entrypoint/dataset.py
  layer/executables/entrypoint/model.py
  layer/main/asset.py
  layer/training/base_train.py
  layer/training/runtime/model_trainer.py
  layer/training/train.py
  test/e2e/test_function_dataset_run.py
  test/unit/test_context.py
  test/unit/test_train.py
Labels: DO NOT MERGE
