Repository layerai/sdk, pull requests merged in 2022-06, with the labels that each got.

#77 Support more model flavors with the prediction API
  layer/flavors/catboost.py
  layer/flavors/lightgbm.py
  layer/flavors/sklearn.py
  layer/flavors/tensorflow.py
  layer/flavors/xgboost.py
Labels: enhancement

#130 Remove sdk dependencies clashing with Colab runtime
  poetry.lock
  pyproject.toml
Labels: dependencies

#140 Support list of dict-s as output of a dataset build function
  layer/decorators/dataset_decorator.py
  layer/utils/runtime_utils.py
  test/unit/utils/__init__.py
  test/unit/utils/test_runtime_utils.py
Labels: enhancement

#155 Fix model train links on local runs
  layer/decorators/model_decorator.py
  layer/training/runtime/model_trainer.py
Labels: bug

#180 Login from entrypoints with access_tokens from the env variables
  layer/decorators/dataset_decorator.py
  layer/decorators/model_decorator.py
  layer/executables/dataset/entrypoint.py
  layer/executables/model/entrypoint.py
Labels: enhancement
